/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AppIndexRouteImport } from './pages/_app/index'
import { Route as AppTasksIndexRouteImport } from './pages/_app/tasks/index'
import { Route as AppAuthIndexRouteImport } from './pages/_app/auth/index'
import { Route as AppTasksTaskIdRouteImport } from './pages/_app/tasks/$taskId'

const AppIndexRoute = AppIndexRouteImport.update({
  id: '/_app/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/_app/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthIndexRoute = AppAuthIndexRouteImport.update({
  id: '/_app/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTasksTaskIdRoute = AppTasksTaskIdRouteImport.update({
  id: '/_app/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/auth': typeof AppAuthIndexRoute
  '/tasks': typeof AppTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/auth': typeof AppAuthIndexRoute
  '/tasks': typeof AppTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app/': typeof AppIndexRoute
  '/_app/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/_app/auth/': typeof AppAuthIndexRoute
  '/_app/tasks/': typeof AppTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tasks/$taskId' | '/auth' | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tasks/$taskId' | '/auth' | '/tasks'
  id:
    | '__root__'
    | '/_app/'
    | '/_app/tasks/$taskId'
    | '/_app/auth/'
    | '/_app/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppTasksTaskIdRoute: typeof AppTasksTaskIdRoute
  AppAuthIndexRoute: typeof AppAuthIndexRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tasks/': {
      id: '/_app/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/auth/': {
      id: '/_app/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AppAuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tasks/$taskId': {
      id: '/_app/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AppTasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppTasksTaskIdRoute: AppTasksTaskIdRoute,
  AppAuthIndexRoute: AppAuthIndexRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
